### ISSUE TITLE
Disconnect not handled

### ISSUE THREAD

**Issue by pergamonster** [60East/amps-client-excel#6]
I built this at work and was able to successfully connect to the server. However, we never got any sows in the drop down. From the server side logs it looks as though the test connection button prompts a cancellation of the connection if successful. So, we get a connection followed by immediate disconnect which isn't handled. Any thoughts?

**Comment by brand** [comment]
Hi @Pergamonster,

can you please open a ticket by sending info to support@crankuptheamps.com so that we can help you resolve your issue? 

Thanks!

**Comment by pergamonster** [comment]
Rebuilt this morning with the fix David pushed and it's working now! Thanks guys

**Comment by davidnoor** [comment]
No problem! Thanks for reporting it; I'll close out the associated support ticket too.
